#!/bin/sh

case $1 in
	config)
		cat <<'EOM'
graph_title conferences
graph_vlabel conferences
graph_category appkonference
graph_info A data point is the sum of all active conferences at the sample time.
conferences.label conferences
EOM
	exit 0;;
esac

echo -n "conferences.value "
asterisk -rx "konference list" | tee /tmp/konferences | sed 1d | wc -l

